### ISSUE TITLE
error when installing via pip

### ISSUE THREAD

**Issue by procmail** [jamespeterschinner/async_v20#21]
``
Collecting async_v20
  Using cached https://files.pythonhosted.org/packages/79/e0/142c9c26d2fc4cadf56ca8fd596c842d5ce6fc47f6b8869c8cd900df27c
f/async_v20-7.0.0b0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wmzjux0u/async-v20/setup.py", line 4, in <module>
        from async_v20 import __version__
      File "/tmp/pip-build-wmzjux0u/async-v20/async_v20/__init__.py", line 3, in <module>
        from async_v20.client import OandaClient
      File "/tmp/pip-build-wmzjux0u/async-v20/async_v20/client.py", line 207
        msg = f'Could not get open trades. ' \
                                           ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wmzjux0u/async-v20/

**Comment by jamespeterschinner** [comment]
Hi mate, did you end up installing async_v20? 

Were you using `pip install async_v20`  in the command line?
